compose: inline logging config because of error
```
./docker-compose-wrapper.sh up -d
gitlab_data_persistence
gitlab_logs_persistence
gitlab_config_persistence
COMPOSE_CONF_LIST=-f docker-compose.yml
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'gitlab-runner'
Unsupported config option for volumes: 'gitlab_data_persistence'
Unsupported config option for x-logging: 'options'
```